#!/usr/local/bin/node

var elasticsearch = require('elasticsearch');
var url = require('url');

var client = new elasticsearch.Client({
  host: process.env.ES_URL
});

client.indices.create({
  index: 'streak'
}).then(function () {
  console.log('"streak" index created!');
});